CREATE TABLE Location (
LocID NUMBER(2,0) NOT NULL,
City CHAR(10 ) NULL,
LocX NUMBER(4,0) NULL,
LocY NUMBER(4,0) NULL,
PRIMARY KEY (LocID) 
)
NOCOMPRESS 
NOPARALLEL ;

CREATE TABLE PWeather (
PDate DATE NOT NULL,
PTime CHAR(10 ) NULL,
LocID NUMBER(2,0) NOT NULL,
Pres VARCHAR2(20) NOT NULL,
PTemp NUMBER(3,1) NOT NULL,
Wind VARCHAR2(20) NULL,
D1 VARCHAR2(20) NULL,
D1MAXT NUMBER(3,1) NULL,
D1MINT NUMBER(3,1) NULL,
D2 VARCHAR2(20) NULL,
D2MAXT NUMBER(3,1) NULL,
D2MINT NUMBER(3,1) NULL,
PRIMARY KEY (PDate) 
)
NOCOMPRESS 
NOPARALLEL ;

CREATE TABLE Schedule (
ScID NUMBER(4,0) NOT NULL,
Sdate DATE NOT NULL,
Stime CHAR(10 ) NOT NULL,
Etime CHAR(10 ) NOT NULL,
Stitle VARCHAR2(30) NOT NULL,
Scontent VARCHAR2(300) NULL,
PRIMARY KEY (ScID) 
)
NOCOMPRESS 
NOPARALLEL ;

CREATE TABLE Weather (
WDate DATE NOT NULL,
D3 VARCHAR2(20) NULL,
D3MAXT NUMBER(3,1) NULL,
D3MINT NUMBER(3,1) NULL,
D4 VARCHAR2(20) NULL,
D4MAXT NUMBER(3,1) NULL,
D4MINT NUMBER(3,1) NULL,
D5 VARCHAR2(20) NULL,
D5MAXT NUMBER(3,1) NULL,
D5MINT NUMBER(3,1) NULL,
D6 VARCHAR2(20) NULL,
D6MAXT NUMBER(3,1) NULL,
D6MINT NUMBER(3,1) NULL,
D7 VARCHAR2(20) NULL,
D7MAXT NUMBER(3,1) NULL,
D7MINT NUMBER(3,1) NULL,
PRIMARY KEY (WDate) 
)
NOCOMPRESS 
NOPARALLEL ;


ALTER TABLE Weather ADD CONSTRAINT FK_37WEATHER_PWEATHER_1 FOREIGN KEY (WDate) REFERENCES PWeather (PDate);
ALTER TABLE PWeather ADD CONSTRAINT FK_PWEATHER_LOCATION_1 FOREIGN KEY (LocID) REFERENCES Location (LocID);

CREATE 
VIEW Bot_DIS AS 
SELECT
PWeather.PDate,
PWeather.LocID,
PWeather.PTime,
PWeather.Pres,
PWeather.PTemp,
PWeather.Wind,
PWeather.D1,
PWeather.D1MAXT,
PWeather.D1MINT,
PWeather.D2,
PWeather.D2MAXT,
PWeather.D2MINT,
Weather.D3,
Weather.D3MAXT,
Weather.D3MINT,
Weather.D4,
Weather.D4MAXT,
Weather.D4MINT,
Weather.D5,
Weather.D5MAXT,
Weather.D5MINT,
Weather.D6,
Weather.D6MAXT,
Weather.D6MINT,
Weather.D7,
Weather.D7MAXT,
Weather.D7MINT

FROM
PWeather
INNER JOIN Weather ON PWeather.PDate = Weather.WDate
WHERE
PWeather.PDate = Weather.WDate AND;

